In [1]:
import numpy as np
from math import *

In [2]:
Sun = 0
Venus = 1
Earth = 2

num_bodies = 3
Dimension = 3

In [3]:
# Data structures hodling the state of the system

pos = np.zeros((num_bodies, Dimension))
vel = np.zeros((num_bodies, Dimension))
acc = np.zeros((num_bodies, Dimension))
mass= np.zeros((num_bodies))

In [4]:
# Physical constants

G_SI = 6.67408e-11      #Gravitational constant in (m^3 kg^-1 s^-2)
M = 1.98855e30          #Solar mass in kg
L = 149597870700        #AU in m
T = 365.256*24*3600     #Sidereal year in seconds
day = 24*3600 / T       #A day in our chosen time unit, for convenience
G = G_SI*M*T**2/L**3    #G in in AU^3 solarmasses^-1 years^-2
c = 63239.7263          #Speed of light in AU/year
alfa = 0
beta = 0

mass[Sun]   = 1.98855e30 / M    #Solar mass: 1 in solar units
mass[Venus] = 4.87e24 / M       #Venus-mass in solar units 
mass[Earth] = 5.972e24 / M      #Earth-mass in solar units
mass

array([1.00000000e+00, 2.44902064e-06, 3.00319328e-06])

In [5]:
#Initial conditions

# Venus
rp_ve = 0.718                                   #Perihelion
ra_ve = 0.728                                   #Aphelion
a_ve = (ra_ve+rp_ve)/2                          #Semi-major axis
init_ve = sqrt(mass[Sun]*G*((2/ra_ve)-(1/a_ve)))#Initial velocity at perihelion
pos[Venus] = np.array([0,ra_ve,0])              #initial position
vel[Venus] = np.array([init_ve, 0, 0])          #initial velocity

# Earth
rp_E = 0.9                                      #Perihelion
ra_E = 1.1                                      #Aphelion
a_E = (ra_E+rp_E)/2                             #Semi-major axis
init_E = sqrt(mass[Sun]*G*((2/ra_E)-(1/a_E)))   #initial velocity at perihelion
pos[Earth] = np.array([0,ra_E,0])               #nitial position
vel[Earth] = np.array([init_E, 0, 0])           #initial velocity

In [6]:
print(pos)
print(vel)

[[0.    0.    0.   ]
 [0.    0.728 0.   ]
 [0.    1.1   0.   ]]
[[0.         0.         0.        ]
 [7.33861879 0.         0.        ]
 [5.68344756 0.         0.        ]]


In [10]:
def grav_acc(pos, mass, acc):
    num_bodies, D = pos.shape
    for i in range(num_bodies):
        acc[i] = np.zeros(3)
        for j in range(num_bodies):
            if j!=i:
                acc[i] += 1 # Gravitational acceleration from body j here
                

In [11]:
print(acc)
grav_acc(pos, mass, acc)
print(acc)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [12]:
def leapfrog(pos, mass, acc, sim_time, dt):
    num_steps = ceil(sim_time/dt)
    num_bodies, D = pos.shape
    
    times = np.zeros((num_steps))
    positions = np.zeros((num_steps, num_bodies, D))
    time = 0
    
    for step in range(num_steps):
        time += dt
        
        # Leapfrog equations here
        # Should calculate mechanical energy also to check its invariance
        times[step] = time
        positions[step] = pos
    
    return times, positions # can return accelerations also 

In [13]:
times, positions = leapfrog(pos, mass, acc, 10, 0.1)

In [14]:
times

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. ])

In [15]:
positions

array([[[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.728, 0.   ],
        [0.   , 1.1  , 0.   ]],

       [[0.   , 0.   , 0.   ],
        [0.   , 0.7